# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy: testwebappsc'
  inputs:
    azureSubscription: CertSC
    appName: testwebappsc
    containers: 'myregistry.azurecr.io/nginx:latest'
    multicontainerConfigFile: '$(System.DefaultWorkingDirectory)/_v-schhabra_pipelines-javascript-docker/app/Dockerfile' 
